---
- name: upload new code and restart the service
  hosts: 10.211.55.11
  vars:
  - app: Appache2/httpd

  tasks: 
  - name: Place custom HTML File
    copy:
      src: /var/lib/jenkins/workspace/webserver-update/index.html
      dest: /var/www/html/index.html
    become: true

  - name: Start the service 
     service: 
       name: Appache2/httpd
       state: restarted
       enabled: yes
    become: true    

